plugins { id 'java-library' }

dependencies {
    api "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    testImplementation platform("org.junit:junit-bom:${junitVersion}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation "net.jqwik:jqwik:${jqwikVersion}"
}
