"""Generates NUMBERS.md from results/*.jsonl. Every figure in the README comes from here.

Usage: python3 bench/ledger.py [results_dir] > NUMBERS.md
"""
import json
import os
import statistics
import sys

R = sys.argv[1] if len(sys.argv) > 1 else "results"
JUDGES = [("kayenta_style", "Kayenta-style judge, once at 6 min"),
          ("sequential", "sequential judge, every 10 s"),
          ("fixed_mw", "Mann-Whitney at alpha/m, once at 6 min"),
          ("peeking_mw", "same, re-checked every 10 s (peeking)"),
          ("peeking_kayenta", "Kayenta-style judge re-checked every 10 s"),
          ("static_flagger", "static limits, Flagger defaults"),
          ("static_tuned", "static limits, tuned on healthy runs")]
ORDER = ["latency_2", "latency_5", "latency_10", "latency_25", "latency_50", "errors_0.5", "errors_2",
         "leak_1k", "leak_4k", "cpu_1ms", "cpu_4ms"]
LABEL = {"latency_2": "latency +2%", "latency_5": "latency +5%", "latency_10": "latency +10%",
         "latency_25": "latency +25%", "latency_50": "latency +50%", "errors_0.5": "errors +0.5% of requests",
         "errors_2": "errors +2% of requests", "leak_1k": "leak 1 KB per request", "leak_4k": "leak 4 KB per request",
         "cpu_1ms": "CPU +1 ms per request", "cpu_4ms": "CPU +4 ms per request", "aa": "A/A (no change)"}


def load(name):
    p = os.path.join(R, name)
    if not os.path.exists(p):
        return []
    with open(p) as f:
        return [json.loads(l) for l in f if l.strip()]


def pct(x, digits=0):
    return f"{100 * x:.{digits}f}%"


def ci(j):
    lo, hi = j["rate_ci95"]
    return f"[{pct(lo)} to {pct(hi)}]"


def wilson(k, n):
    if n == 0:
        return 0.0, 1.0
    z = 1.959963984540054
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * ((p * (1 - p) / n + z * z / (4 * n * n)) ** 0.5) / d
    return max(0.0, c - h), min(1.0, c + h)


def fmt_min(x):
    return "" if x is None else f"{x:.1f}"


def main():
    out = []
    w = out.append
    trials = load("trials.jsonl")
    judgements = load("judgements.jsonl")
    exp1 = {r["scenario"]: r for r in load("exp1.jsonl")}
    exp2 = load("exp2.jsonl")
    exp3 = {r["scenario"]: r for r in load("exp3.jsonl")}
    exp4 = load("exp4.jsonl")
    exp5 = load("exp5.jsonl")
    sim = load("sim_aa.jsonl")
    trace = load("trace_judgements_summary.jsonl")
    argo = load("argo.jsonl")

    w("# NUMBERS\n")
    w("Every figure CanaryJudge reports, generated by `bench/ledger.py` from `results/*.jsonl`. Each section names the file its rows come from.\n")
    if trials:
        m = trials[0]["meta"]["machine"]
        loads = [t["meta"][k].get("windows_host_cpu_pct") for t in trials for k in ("load_before", "load_after") if t["meta"].get(k)]
        loads = [x for x in loads if x is not None]
        wsl = [t["meta"]["load_after"].get("wsl_load1") for t in trials if t["meta"].get("load_after")]
        w(f"**Machine.** One shared mini PC: {m['cpu']} ({m['cores_host']} cores), {m['ram_gb_host']} GB, Windows 11 with WSL2 "
          f"({m['wsl_vcpus']} vCPU, {m['wsl_mem_gb']} GB). Every target, Prometheus, the splitter, the load generator and the judges run "
          f"in that VM. Other jobs share the box, so each run records the host load: Windows host CPU {min(loads):.0f}% to {max(loads):.0f}% "
          f"at the start and end of the runs, WSL 1-minute load {min(wsl):.1f} to {max(wsl):.1f}.\n")
        w("**Workload.** A sample Spring Boot service (`target/`) whose requests wait on a simulated dependency (log-normal, median 20 ms) "
          "and fail at a 0.1% background rate. Each live canary is a fresh baseline and a fresh canary started together, each taking half "
          "of 80 requests per second from an open-loop load generator (Poisson arrivals, Zipf-distributed users), measured for 6 minutes "
          "after a 90 s warm-up, sampled every 10 s from 2 s Prometheus scrapes. Regressions are injected into the canary. "
          "Not production traffic and not a production service.\n")

    if trials:
        by = {}
        for t in trials:
            by.setdefault(t["scenario"], 0)
            by[t["scenario"]] += 1
        w("## The recorded runs (`results/trials.jsonl`)\n")
        w(f"{len(trials)} live canary runs: " + ", ".join(f"{LABEL.get(k, k)} {v}" for k, v in sorted(by.items())) + ". "
          "The calibration runs only set the tuned static thresholds and are not scored. Runs rejected for losing traffic are in "
          "`results/trials_rejected.jsonl` (if any) and were re-run.\n")

    if exp1:
        w("## exp1: detection rate per regression (`results/exp1.jsonl`)\n")
        w("Share of runs in which each judge stopped the canary within the 6-minute window. The Kayenta-style judge counts as stopping "
          "the canary when its score is below the pass threshold (95).\n")
        w("| regression | runs | " + " | ".join(lbl for _, lbl in JUDGES) + " |")
        w("|---|---|" + "---|" * len(JUDGES))
        for s in ORDER:
            if s not in exp1:
                continue
            r = exp1[s]
            w(f"| {LABEL[s]} | {r['runs']} | " + " | ".join(f"{pct(r[j]['rate'])} ({r[j]['failed']})" for j, _ in JUDGES) + " |")
        tot = {j: [0, 0] for j, _ in JUDGES}
        for s in ORDER:
            if s in exp1:
                for j, _ in JUDGES:
                    tot[j][0] += exp1[s][j]["failed"]
                    tot[j][1] += exp1[s]["runs"]
        w("| **all injected regressions** | " + str(tot["sequential"][1]) + " | " +
          " | ".join(f"**{pct(tot[j][0] / tot[j][1])}** ({tot[j][0]})" for j, _ in JUDGES) + " |")
        w("")
        big = [s for s in ORDER if s in exp1 and s not in ("latency_2", "latency_5")]
        bt = {j: [sum(exp1[s][j]["failed"] for s in big), sum(exp1[s]["runs"] for s in big)] for j, _ in JUDGES}
        w("Without the two smallest latency regressions (+2%, +5%): " +
          ", ".join(f"{lbl} {pct(bt[j][0] / bt[j][1])}" for j, lbl in JUDGES[:2]) +
          f" of {bt['sequential'][1]} runs.\n")

    if exp2:
        r = exp2[0]
        w("## exp2: false alarms on A/A canaries (`results/exp2.jsonl`)\n")
        w(f"{r['runs']} runs where baseline and canary are the same build. A failure here is a false alarm. 95% Wilson intervals.\n")
        w("| judge | false alarms | rate | 95% interval |")
        w("|---|---|---|---|")
        for j, lbl in JUDGES:
            w(f"| {lbl} | {r[j]['failed']} of {r['runs']} | {pct(r[j]['rate'], 1)} | {ci(r[j])} |")
        ac = r.get("mean_lag1_autocorrelation_of_differences", {})
        if ac:
            w("\nMean lag-1 autocorrelation of the per-interval differences (canary minus baseline) in these runs; the sequential "
              "t-test assumes 0: " + ", ".join(f"{k} {v:+.2f}" for k, v in ac.items()) + ".\n")

    trace_aa = [r for r in load("trace/exp2.jsonl") if r["scenario"] == "aa"]
    if trace_aa and exp2:
        r2, rt = exp2[0], trace_aa[0]
        w("### All live A/A canaries together\n")
        w(f"The {r2['runs']} A/A runs above plus the {rt['runs']} A/A runs under the replayed NASA trace (native Windows, "
          "`results/trace/exp2.jsonl`). A second native A/A set was attempted and abandoned: 0 of 6 attempts passed the traffic "
          "check while other jobs held the host CPU near 100% (`results/trials_native_aa.log`).\n")
        w("| judge | false alarms | rate | 95% interval |")
        w("|---|---|---|---|")
        for j, lbl in JUDGES:
            k, n = r2[j]["failed"] + rt[j]["failed"], r2["runs"] + rt["runs"]
            lo, hi = wilson(k, n)
            w(f"| {lbl} | **{k} of {n}** | {pct(k / n, 1)} | [{pct(lo)} to {pct(hi)}] |")
        w("")

    native = load("native/exp2.jsonl")
    if native and exp2:
        r2, rn = exp2[0], native[0]
        w("### exp2, second set: A/A canaries run natively on Windows (`results/native/exp2.jsonl`)\n")
        w(f"{rn['runs']} more healthy canaries, from `results/trials_native_aa.jsonl`, on the same mini PC as native Windows processes "
          "(no WSL, no Docker), while other jobs kept the host CPU near 100%. Same judges, same config.\n")
        w("| judge | false alarms, native set | both sets together | 95% interval, both sets |")
        w("|---|---|---|---|")
        for j, lbl in JUDGES:
            k = r2[j]["failed"] + rn[j]["failed"]
            n = r2["runs"] + rn["runs"]
            lo, hi = wilson(k, n)
            w(f"| {lbl} | {rn[j]['failed']} of {rn['runs']} | **{k} of {n}** ({pct(k / n, 1)}) | [{pct(lo)} to {pct(hi)}] |")
        w("")

    if exp3:
        w("## exp3: time to stop a bad canary (`results/exp3.jsonl`)\n")
        w("Minutes from the start of the measured window until the judge failed the canary, over the runs it caught. The fixed-horizon "
          "judges decide once, at 6 minutes. Median and 90th percentile.\n")
        w("| regression | runs | sequential: caught | sequential: median min | sequential: p90 min | fixed horizon (Kayenta-style): caught | fixed: minutes |")
        w("|---|---|---|---|---|---|---|")
        seq_all, fix_all = [], []
        for s in ORDER:
            if s not in exp3:
                continue
            r = exp3[s]
            sq, fx = r["sequential"], r["fixed_horizon_kayenta_style"]
            w(f"| {LABEL[s]} | {r['runs']} | {pct(sq['rate'])} | {fmt_min(sq['median_minutes_to_fail'])} | {fmt_min(sq['p90_minutes_to_fail'])} | "
              f"{pct(fx['rate'])} | {r['fixed_horizon_minutes']:.0f} |")
        for j in judgements:
            if j["scenario"] in ORDER and j["sequential"]["failed"]:
                seq_all.append(j["sequential"]["minutes_to_fail"])
        if seq_all:
            w(f"\nOver every injected run the sequential judge caught ({len(seq_all)} runs): median "
              f"**{statistics.median(seq_all):.1f} min** to stop the canary, against 6 min for the fixed-horizon judge.\n")

    if exp4:
        summ = [r for r in exp4 if r["exp"] == "exp4_summary"]
        if summ:
            s = summ[-1]
            w("## exp4: agreement with Kayenta (`results/exp4.jsonl`)\n")
            w(f"Kayenta itself (`{s['kayenta_image']}`, unmodified) and CanaryJudge judged the same recorded series, every run at "
              f"{', '.join(str(x) for x in s['windows'])} intervals ({s['judgements']} judgments of {s['runs']} runs). CanaryJudge "
              f"was called through its Kayenta-compatible API, and again in process (`results/exp4_inprocess.jsonl`, the same "
              f"result). This ran on a {s['machine']['host']}, because Docker on the mini PC was unavailable by then "
              f"(BUG_LOG #9); the judgments are deterministic, so the machine does not change them.\n")
            w(f"- Per-metric classification: **{s['metric_verdicts_agree']:,} of {s['metric_verdicts_compared']:,}** agree.")
            w(f"- Canary verdict (Pass, Marginal, Fail): **{s['canary_verdicts_agree']} of {s['judgements']}** agree.")
            w(f"- Largest score difference: {s['max_score_diff']:.2f}.")
            if s["disagreements"]:
                w("- Disagreements: " + "; ".join(s["disagreements"][:20]))
            nonpass = sum(1 for r in exp4 if r["exp"] == "exp4" for m in r["metrics"] if m["kayenta"] != "Pass")
            w(f"- Of the compared classifications, {nonpass:,} were not Pass in Kayenta (so agreement covers failures, not just passes).\n")

    if exp5:
        w("## exp5: live rollouts (`results/exp5.jsonl`)\n")
        w("The rollout controller moves a fresh canary through 1%, 5% and 25% of users (2 minutes each, a fresh baseline at the same "
          "share), then promotes it. Users stick to one side by a hash of their id; the share of users who reached the canary is "
          "counted by the splitter from the start of the rollout to the end (rollback or promotion). These ran as native Windows "
          "processes on the same mini PC (Prometheus's Windows binary, every service a plain JVM on 127.0.0.1), because Docker in "
          "WSL had become unusable (BUG_LOG #9). The load generator sends 200 requests per second to the rollout lane.\n")
        w("| regression | judge | rollouts | rolled back | median minutes to rollback | median share of users reached | max share of users reached |")
        w("|---|---|---|---|---|---|---|")
        groups = {}
        for r in exp5:
            groups.setdefault((r["scenario"], r["mode"]), []).append(r)
        for (s, mode), rs in sorted(groups.items(), key=lambda kv: (["aa"] + ORDER).index(kv[0][0]) * 2 + (kv[0][1] == "fixed")):
            rb = [r for r in rs if r["status"] == "rolled_back"]
            mins = [r["seconds"] / 60 for r in rb]
            shares = [r["canary_user_share"] for r in rs]
            w(f"| {LABEL.get(s, s)} | {mode} | {len(rs)} | {len(rb)} | {fmt_min(statistics.median(mins)) if mins else ''} | "
              f"{pct(statistics.median(shares), 2)} | {pct(max(shares), 2)} |")
        bad = [r for r in exp5 if r["scenario"] != "aa" and r["mode"] == "sequential"]
        fast = [r for r in bad if r["status"] == "rolled_back" and r["scenario"].split("_")[0] in ("latency", "errors", "cpu")]
        if fast:
            w(f"\nSequential judge, latency, error and CPU regressions it rolled back ({len(fast)} rollouts): at most "
              f"**{pct(max(r['canary_user_share'] for r in fast), 1)}** of users reached the canary, median "
              f"{statistics.median(r['seconds'] for r in fast) / 60:.1f} minutes to rollback.")
        if bad:
            w(f"\nSequential judge, every injected regression ({len(bad)} rollouts): at most **{pct(max(r['canary_user_share'] for r in bad), 1)}** "
              f"of users reached the bad canary before rollback; {sum(r['status'] == 'rolled_back' for r in bad)} of {len(bad)} rolled back.\n")
        w("Manual 30-minute canary, for comparison (a model, not a measurement): a canary at 5% of users for 30 minutes exposes 5% of "
          "users when the regression is caught at the end, and every user when it is missed and promoted. With the miss rates of the "
          "tuned static limits from exp1 (the closest thing to a person watching dashboards), the expected share is listed per regression "
          "in `results/exp5_manual_model.jsonl`.\n")

    if sim:
        w("## A/A simulation: peeking versus the sequential test (`results/sim_aa.jsonl`)\n")
        w("Synthetic healthy canaries (not live data): per-interval latency for baseline and canary from the same log-normal, with a "
          "load term shared by both sides (or none), and AR(1) noise with autocorrelation phi. A shared load term makes the unpaired "
          "Mann-Whitney test conservative (it ignores the pairing); with independent sides it sits at its nominal 5%. One metric, one-sided, alpha 5%. False-alarm rate after a given "
          "number of checks.\n")
        looks = sorted({r["looks"] for r in sim})
        w("| shared load | phi | method | " + " | ".join(f"{l} checks" for l in looks) + " |")
        w("|---|---|---|" + "---|" * len(looks))
        rows = {}
        for r in sim:
            rows.setdefault((r.get("load_sd", 0.0), r["phi"], r["method"]), {})[r["looks"]] = r
        for (ld, phi, method), d in sorted(rows.items()):
            w(f"| {'yes' if ld else 'no'} | {phi} | {method} | " + " | ".join(pct(d[l]["rate"], 1) if l in d else "" for l in looks) + " |")
        w(f"\n{sim[0]['runs']} runs per cell, seed {sim[0]['seed']}. The fixed row is one test at that horizon (one check).\n")

    if trace:
        w("## Real-shaped traffic (`results/trace_judgements_summary.jsonl`)\n")
        w("The same judges on canaries run under a replay of the NASA-KSC web server's request rate (July 1995, per minute, "
          "from 3 July 09:00, one trace minute per 10 s of wall time, 40 requests per second per lane at the trace's mean), run "
          "natively on Windows on the same mini PC from `results/trace_trials.jsonl`. 11 of 12 planned runs were accepted; the "
          "rest of the attempts were rejected by the traffic check while other jobs held the host CPU near 100% "
          "(`results/trace_trials.log`). Too few runs for rates; it shows the judges behave the same under a real traffic shape.\n")
        w("| scenario | runs | " + " | ".join(lbl for _, lbl in JUDGES[:3]) + " |")
        w("|---|---|" + "---|" * 3)
        for r in trace:
            w(f"| {LABEL.get(r['scenario'], r['scenario'])} | {r['runs']} | " + " | ".join(f"{pct(r[j]['rate'])} ({r[j]['failed']})" for j, _ in JUDGES[:3]) + " |")
        w("")

    if argo:
        w("## Argo Rollouts integration (`results/argo.jsonl`)\n")
        for r in argo:
            w(f"- {r['ts']}: {r['description']}: {r['outcome']}")
        w("")
    print("\n".join(out))


if __name__ == "__main__":
    main()
